import { apiFetch } from "./api";
import { useEffect, useState } from "react";
import {
  Bell,
  RefreshCw,
  ShieldAlert,
  Clock,
  CheckCircle2,
  AlertTriangle,
} from "lucide-react";

const API = "http://127.0.0.1:8001";

type AlertItem = {
  id?: number | string;
  alert_id?: number | string;
  title?: string;
  name?: string;
  description?: string;
  message?: string;
  severity?: string;
  risk_score?: number;
  score?: number;
  status?: string;
  source?: string;
  ioc?: string;
  ioc_value?: string;
  created_at?: string;
  timestamp?: string;
};

export default function Alerts() {
  const [alerts, setAlerts] = useState<AlertItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [lastChecked, setLastChecked] = useState("");

  const loadAlerts = async () => {
    try {
      setLoading(true);
      setError("");

      const response = await apiFetch(`${API}/api/alerts`);

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }

      const data = await response.json();

      const list = Array.isArray(data)
        ? data
        : Array.isArray(data.alerts)
        ? data.alerts
        : Array.isArray(data.items)
        ? data.items
        : [];

      setAlerts(list);
      setLastChecked(new Date().toLocaleTimeString());
    } catch (err) {
      setAlerts([]);
      setError(
        err instanceof Error ? err.message : "Unable to load alerts"
      );
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAlerts();
  }, []);

  const getSeverity = (alert: AlertItem) => {
    const value = String(alert.severity || "").toLowerCase();

    if (value.includes("critical")) return "CRITICAL";
    if (value.includes("high")) return "HIGH";
    if (value.includes("medium")) return "MEDIUM";
    if (value.includes("low")) return "LOW";

    const score = Number(alert.risk_score ?? alert.score ?? 0);

    if (score >= 85) return "CRITICAL";
    if (score >= 60) return "HIGH";
    if (score >= 30) return "MEDIUM";
    return "LOW";
  };

  const getStatus = (alert: AlertItem) => {
    return String(alert.status || "OPEN").toUpperCase();
  };

  const severityClass = (severity: string) => {
    if (severity === "CRITICAL") return "alert-critical";
    if (severity === "HIGH") return "alert-high";
    if (severity === "MEDIUM") return "alert-medium";
    return "alert-low";
  };

  const openCount = alerts.filter(
    (a) => !["RESOLVED", "CLOSED"].includes(getStatus(a))
  ).length;

  const criticalCount = alerts.filter(
    (a) => getSeverity(a) === "CRITICAL"
  ).length;

  return (
    <div className="page-container">
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 24,
        }}
      >
        <div>
          <h1>Alerts</h1>
          <p>Monitor and investigate security alerts generated by ThreatLens.</p>
        </div>

        <button
          onClick={loadAlerts}
          disabled={loading}
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
          }}
        >
          <RefreshCw size={16} />
          {loading ? "Checking..." : "Refresh"}
        </button>
      </div>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(3, 1fr)",
          gap: 16,
          marginBottom: 24,
        }}
      >
        <div className="stat-card">
          <span>TOTAL ALERTS</span>
          <strong>{alerts.length}</strong>
        </div>

        <div className="stat-card">
          <span>OPEN ALERTS</span>
          <strong>{openCount}</strong>
        </div>

        <div className="stat-card">
          <span>CRITICAL</span>
          <strong>{criticalCount}</strong>
        </div>
      </div>

      {error && (
        <div
          style={{
            padding: 16,
            marginBottom: 18,
            borderRadius: 10,
            border: "1px solid rgba(255,80,100,.3)",
            background: "rgba(255,40,70,.06)",
          }}
        >
          <strong>Unable to load alerts</strong>
          <div style={{ marginTop: 6, opacity: 0.75 }}>{error}</div>
        </div>
      )}

      {!error && !loading && alerts.length === 0 && (
        <div
          className="card"
          style={{
            padding: 50,
            textAlign: "center",
          }}
        >
          <Bell size={42} style={{ opacity: 0.45 }} />
          <h2>No alerts yet</h2>
          <p>
            ThreatLens has not generated any alerts yet.
          </p>
        </div>
      )}

      <div style={{ display: "grid", gap: 14 }}>
        {alerts.map((alert, index) => {
          const severity = getSeverity(alert);
          const status = getStatus(alert);

          const id =
            alert.id ??
            alert.alert_id ??
            index + 1;

          const indicator =
            alert.ioc_value ??
            alert.ioc ??
            "No IOC value";

          const title =
            alert.title ??
            alert.name ??
            `Security Alert #${id}`;

          const description =
            alert.description ??
            alert.message ??
            "ThreatLens security alert";

          const created =
            alert.created_at ??
            alert.timestamp ??
            "Unknown";

          return (
            <div
              className="card"
              key={String(id)}
              style={{
                padding: 20,
                borderRadius: 14,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  gap: 20,
                }}
              >
                <div style={{ display: "flex", gap: 14 }}>
                  <div
                    style={{
                      width: 44,
                      height: 44,
                      borderRadius: 12,
                      display: "grid",
                      placeItems: "center",
                      background: "rgba(70,90,180,.12)",
                    }}
                  >
                    <ShieldAlert size={22} />
                  </div>

                  <div>
                    <h3 style={{ margin: 0 }}>{title}</h3>

                    <div
                      style={{
                        marginTop: 6,
                        fontSize: 13,
                        opacity: 0.7,
                      }}
                    >
                      IOC: {indicator}
                    </div>

                    <div
                      style={{
                        marginTop: 8,
                        fontSize: 14,
                      }}
                    >
                      {description}
                    </div>
                  </div>
                </div>

                <div
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "flex-end",
                    gap: 8,
                  }}
                >
                  <span className={severityClass(severity)}>
                    <AlertTriangle size={13} />
                    {severity}
                  </span>

                  <span
                    style={{
                      fontSize: 12,
                      opacity: 0.75,
                    }}
                  >
                    {status}
                  </span>
                </div>
              </div>

              <div
                style={{
                  marginTop: 18,
                  paddingTop: 14,
                  borderTop: "1px solid rgba(100,120,160,.15)",
                  display: "flex",
                  gap: 22,
                  fontSize: 12,
                  opacity: 0.7,
                }}
              >
                <span>
                  <Clock size={13} style={{ verticalAlign: "middle" }} />{" "}
                  {created}
                </span>

                {alert.source && (
                  <span>
                    Source: {alert.source}
                  </span>
                )}

                {(alert.risk_score ?? alert.score) !== undefined && (
                  <span>
                    Risk: {alert.risk_score ?? alert.score}/100
                  </span>
                )}

                {["RESOLVED", "CLOSED"].includes(status) && (
                  <span>
                    <CheckCircle2
                      size={13}
                      style={{ verticalAlign: "middle" }}
                    />{" "}
                    Resolved
                  </span>
                )}
              </div>
            </div>
          );
        })}
      </div>

      <div
        style={{
          marginTop: 20,
          fontSize: 12,
          opacity: 0.55,
        }}
      >
        Last checked: {lastChecked || "—"}
      </div>
    </div>
  );
}
