import { apiFetch } from "./api";
import { useEffect, useState } from "react";
import {
  AlertTriangle,
  CheckCircle2,
  Clock,
  RefreshCw,
  ShieldAlert,
  Search,
} from "lucide-react";

const API = "http://127.0.0.1:8001";

type Incident = {
  id: number;
  title: string;
  severity: string;
  status: string;
  alert_id: number | null;
  description: string | null;
  created_at: string;
};

export default function Incidents() {
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [loading, setLoading] = useState(true);
  const [updating, setUpdating] = useState<number | null>(null);
  const [error, setError] = useState("");
  const [lastChecked, setLastChecked] = useState("");

  const loadIncidents = async () => {
    try {
      setLoading(true);
      setError("");

      const response = await apiFetch(`${API}/api/incidents/`);

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }

      const data = await response.json();

      setIncidents(Array.isArray(data) ? data : []);
      setLastChecked(new Date().toLocaleTimeString());
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Unable to load incidents"
      );
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadIncidents();
  }, []);

  const updateStatus = async (
    incidentId: number,
    status: string
  ) => {
    try {
      setUpdating(incidentId);
      setError("");

      const response = await apiFetch(
        `${API}/api/incidents/${incidentId}/status?status=${encodeURIComponent(
          status
        )}`,
        {
          method: "PATCH",
        }
      );

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }

      await loadIncidents();
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Unable to update incident"
      );
    } finally {
      setUpdating(null);
    }
  };

  const openCount = incidents.filter(
    (x) => x.status.toLowerCase() === "open"
  ).length;

  const investigatingCount = incidents.filter(
    (x) => x.status.toLowerCase() === "investigating"
  ).length;

  const criticalCount = incidents.filter(
    (x) => x.severity.toLowerCase() === "critical"
  ).length;

  const severityClass = (severity: string) => {
    const value = severity.toLowerCase();

    if (value === "critical") return "alert-critical";
    if (value === "high") return "alert-high";
    if (value === "medium") return "alert-medium";
    return "alert-low";
  };

  return (
    <div className="page-container">
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 24,
        }}
      >
        <div>
          <h1>Incidents</h1>
          <p>
            Investigate and manage security incidents generated by ThreatLens.
          </p>
        </div>

        <button
          onClick={loadIncidents}
          disabled={loading}
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
          }}
        >
          <RefreshCw size={16} />
          {loading ? "Loading..." : "Refresh"}
        </button>
      </div>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(4, 1fr)",
          gap: 16,
          marginBottom: 24,
        }}
      >
        <div className="stat-card">
          <span>TOTAL INCIDENTS</span>
          <strong>{incidents.length}</strong>
        </div>

        <div className="stat-card">
          <span>OPEN</span>
          <strong>{openCount}</strong>
        </div>

        <div className="stat-card">
          <span>INVESTIGATING</span>
          <strong>{investigatingCount}</strong>
        </div>

        <div className="stat-card">
          <span>CRITICAL</span>
          <strong>{criticalCount}</strong>
        </div>
      </div>

      {error && (
        <div
          style={{
            padding: 16,
            marginBottom: 18,
            borderRadius: 10,
            border: "1px solid rgba(255,80,100,.3)",
            background: "rgba(255,40,70,.06)",
          }}
        >
          <strong>Incident operation failed</strong>
          <div style={{ marginTop: 6, opacity: 0.75 }}>
            {error}
          </div>
        </div>
      )}

      {!loading && !error && incidents.length === 0 && (
        <div
          className="card"
          style={{
            padding: 50,
            textAlign: "center",
          }}
        >
          <ShieldAlert
            size={44}
            style={{ opacity: 0.45 }}
          />
          <h2>No incidents</h2>
          <p>No security incidents are currently recorded.</p>
        </div>
      )}

      <div style={{ display: "grid", gap: 16 }}>
        {incidents.map((incident) => {
          const severity = incident.severity.toUpperCase();

          return (
            <div
              className="card"
              key={incident.id}
              style={{
                padding: 22,
                borderRadius: 14,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  gap: 20,
                }}
              >
                <div
                  style={{
                    display: "flex",
                    gap: 14,
                  }}
                >
                  <div
                    style={{
                      width: 46,
                      height: 46,
                      borderRadius: 12,
                      display: "grid",
                      placeItems: "center",
                      background: "rgba(70,90,180,.12)",
                    }}
                  >
                    <AlertTriangle size={23} />
                  </div>

                  <div>
                    <h3 style={{ margin: 0 }}>
                      {incident.title}
                    </h3>

                    <div
                      style={{
                        marginTop: 7,
                        fontSize: 13,
                        opacity: 0.7,
                      }}
                    >
                      Incident #{incident.id}
                      {incident.alert_id !== null &&
                        ` • Alert #${incident.alert_id}`}
                    </div>

                    <p
                      style={{
                        marginTop: 10,
                        marginBottom: 0,
                      }}
                    >
                      {incident.description ||
                        "No description available."}
                    </p>
                  </div>
                </div>

                <span className={severityClass(severity)}>
                  <AlertTriangle size={13} />
                  {severity}
                </span>
              </div>

              <div
                style={{
                  marginTop: 20,
                  paddingTop: 15,
                  borderTop:
                    "1px solid rgba(100,120,160,.15)",
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  gap: 15,
                  flexWrap: "wrap",
                }}
              >
                <div
                  style={{
                    display: "flex",
                    gap: 18,
                    fontSize: 12,
                    opacity: 0.7,
                  }}
                >
                  <span>
                    <Clock
                      size={13}
                      style={{ verticalAlign: "middle" }}
                    />{" "}
                    {new Date(
                      incident.created_at
                    ).toLocaleString()}
                  </span>

                  <span>
                    Status:{" "}
                    <strong>
                      {incident.status.toUpperCase()}
                    </strong>
                  </span>
                </div>

                <div
                  style={{
                    display: "flex",
                    gap: 8,
                    flexWrap: "wrap",
                  }}
                >
                  <button
                    disabled={updating === incident.id}
                    onClick={() =>
                      updateStatus(
                        incident.id,
                        "open"
                      )
                    }
                  >
                    Open
                  </button>

                  <button
                    disabled={updating === incident.id}
                    onClick={() =>
                      updateStatus(
                        incident.id,
                        "investigating"
                      )
                    }
                  >
                    <Search
                      size={14}
                      style={{
                        verticalAlign: "middle",
                        marginRight: 4,
                      }}
                    />
                    Investigate
                  </button>

                  <button
                    disabled={updating === incident.id}
                    onClick={() =>
                      updateStatus(
                        incident.id,
                        "resolved"
                      )
                    }
                  >
                    <CheckCircle2
                      size={14}
                      style={{
                        verticalAlign: "middle",
                        marginRight: 4,
                      }}
                    />
                    Resolve
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      <div
        style={{
          marginTop: 20,
          fontSize: 12,
          opacity: 0.55,
        }}
      >
        Last checked: {lastChecked || "—"}
      </div>
    </div>
  );
}
